version: "3.8"
services:
  redis:
    image: redis
    container_name: redis
    init: true
    volumes:
      - ./r-dump:/r-dump
      - ./redis-backup.sh:/redis-backup.sh
    ports:
      - "_:6379"
    entrypoint: ["/bin/bash", "-c", "/redis-dump.sh"]

  watcher:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "_:5000"
    environment:
      - PORT=5000
      - NODE_ENV=prod
      - DB_URL=mongodb+srv://parnetwork03:FDpTIkjSws24neHg@genxi.tiaymzj.mongodb.net/watcher
      - SLACK_TOKEN=xoxb-8184291399011-8170433298871-y9YeNSNN7mt9dlKR1spyE4be
      - SLACK_CHANNEL_ID=C0857NJJCG6
      - RABBITMQ_URL=amqps://vgvxrvyi:JF_OtuJ7DcmvwSJ2b6bRmKcfxFYMlRA1@puffin.rmq2.cloudamqp.com/vgvxrvyi
      - JWT_SECRET=OKOIjkdmfekr83495rijfdkfls'OFRKEOFKml,drbhfjgeryi
      - REDIS_URL=redis://redis/
    depends_on:
      redis:
        condition: service_healthy
    restart: always
