version: "3.8"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Uyh98yuHUy739J&*^e37hu
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - "5672:5672"
      - "15672:15672"

  watcher:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    environment:
      - PORT=5000
      - NODE_ENV=prod
      - DB_URL=mongodb://host.docker.internal:27017/watcher
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://admin:Uyh98yuHUy739J&*^e37hu@rabbitmq:5672
    depends_on:
      - redis
      - rabbitmq
