version: "3.8"
services:
  watcher-redis-server:
    image: redis
    ports:
      - "6379:6379"

  watcher:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=prod
      - DB_URL=mongodb://host.docker.internal:27017/watcher
      - RABBITMQ_URL=amqps://fpmfviyh:JywFmX2sUulZJpE_66SGtwrcsZrHRxpH@puffin.rmq2.cloudamqp.com/fpmfviyh
      - JWT_SECRET=OKOIjkdmfekr83495rijfdkfls'OFRKEOFKml,drbhfjgeryi
      - REDIS_URL=redis://watcher-redis-server
    restart: always
