version: "3.8"
services:
  watcher-redis-server:
    image: redis
    init: true
    volumes:
      - ./r-dump:/r-dump
      - ./redis-backup.sh:/redis-backup.sh
    ports:
      - "3219:6379"
    entrypoint: ["/bin/bash", "-c", "/redis-backup.sh"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  watcher:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3218:5000"
    environment:
      - PORT=5000
      - NODE_ENV=prod
      - DB_URL=mongodb+srv://parnetwork03:FDpTIkjSws24neHg@genxi.tiaymzj.mongodb.net/watcher
      - RABBITMQ_URL=amqps://obmslcja:mqaaa6iaKCUm1TW50ug1NCiEJZV_uVFu@puffin.rmq2.cloudamqp.com/obmslcja
      - JWT_SECRET=OKOIjkdmfekr83495rijfdkfls'OFRKEOFKml,drbhfjgeryi
      - REDIS_URL=redis://watcher-redis-server
      - REDIS_PASSWORD=efu*&8hsdjer83HUEHWru;isjd
    restart: always
    depends_on:
      - watcher-redis-server
