version: "3.8"
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=88uUHEefh9*&^dghf8ehfue&*Y
    command: ["redis-server", "--requirepass", "88uUHEefh9*&^dghf8ehfue&*Y"]

  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Uyh98yuHUy739J&*^e37hu
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s
    ports:
      - "5672:5672"
      - "15672:15672"

  watcher:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=prod
      - DB_URL=mongodb+srv://parnetwork03:FDpTIkjSws24neHg@genxi.tiaymzj.mongodb.net/rabbitvpn
      - BACKEND_URL=http://103.116.176.223:3201
