version: "3.8"
services:
  watcher:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3218:5000"
    environment:
      - PORT=5000
      - NODE_ENV=prod
      - DB_URL=mongodb+srv://parnetwork03:FDpTIkjSws24neHg@genxi.tiaymzj.mongodb.net/watcher
      - RABBITMQ_URL=amqps://vgvxrvyi:JF_OtuJ7DcmvwSJ2b6bRmKcfxFYMlRA1@puffin.rmq2.cloudamqp.com/vgvxrvyi
      - JWT_SECRET=OKOIjkdmfekr83495rijfdkfls'OFRKEOFKml,drbhfjgeryi
      - REDIS_URL=redis://default:AXciAAIjcDFjNWU0NTdiOTUwOTA0ZjE4OGRmOTI4NTEyZjUxYTBiN3AxMA@renewing-stork-30498.upstash.io:6379
    restart: always
