FROM node:20

ENV TZ=Asia/Kolkata

RUN apt-get update && apt-get install -y tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apt-get clean
    
WORKDIR /app

COPY ./package.json ./
RUN npm install

COPY ./ ./

CMD ["npm", "run", "watch"]