version: "3.8"
services:
  watcher:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=prod
      - DB_URL=mongodb://host.docker.internal:27017/watcher
      - RABBITMQ_URL=amqps://vgvxrvyi:JF_OtuJ7DcmvwSJ2b6bRmKcfxFYMlRA1@puffin.rmq2.cloudamqp.com/vgvxrvyi
      - JWT_SECRET=OKOIjkdmfekr83495rijfdkfls'OFRKEOFKml,drbhfjgeryi
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis
    restart: always
